zephyr:
  # Change this value based on your model and your GPU VRAM pool.
  n_gpu_layers: 1
  # Should be between 1 and n_ctx, consider the amount of VRAM in your GPU.
  n_batch: 512
  temperature: 0
  model_name: 'zephyr-7b-beta.Q5_K_M.gguf'
  max_tokens: 2000
  top_p: 0.95
  top_k: 20